apiVersion: apps/v1
kind: Deployment
metadata:
    name: gameoflife-image-deploy
spec:
    replicas: 1
    selector:
    matchLabels:
      app:  gameoflife-image-ctr
    template:
      metadata:
       labels:
         app:  gameoflife-image-ctr
      spec:
         containers:
         - name:  gameoflife-image-pod
           image: docker.io/ravigopireddy299/gameoflife-image:latest
           ports:
           - containerPort: 8080
