apiVersion: apps/v1
kind: Deployment
metadata:
    name: gol-deploy
spec:
    replicas: 1
    selector:
    matchLabels:
      app: gol-ctr
      commit: $CI_COMMIT_SHA
    template:
      metadata:
       labels:
         app: gol-ctr
         commit: $CI_COMMIT_SHA
      spec:
         containers:
         - name: gol-pod
           image: docker.io/ravigopireddy299/gameoflife-image:latest
           ports:
           - containerPort: 8080
