apiVersion: v1
kind: Service
metadata: 
  name: gameoflife-image-svc
  labels:
    app: gameoflife-image-ctr
spec:
  type: NodePort
  ports: 
  - port: 8080
    nodePort: 30005
    protocol: TCP
  selector:
    app: gameoflife-image-ctr
